#!/bin/bash
# LocalStack Quick Reference / Cheat Sheet

echo "🛡️  Cloud Policy Guard - LocalStack Quick Reference"
echo "=================================================="
echo ""
echo "📝 BASIC COMMANDS"
echo "─────────────────────────────────────────────────"
echo ""
echo "Start LocalStack:"
echo "  ./localstack-start.sh"
echo ""
echo "Stop LocalStack:"
echo "  ./localstack-stop.sh"
echo ""
echo "Check if LocalStack is running:"
echo "  docker ps | grep localstack"
echo ""
echo "🔍 SCANNING"
echo "─────────────────────────────────────────────────"
echo ""
echo "Scan security groups in LocalStack:"
echo "  java -jar target/cloud-policy-guard.jar scan-aws \\"
echo "    --region us-east-1 \\"
echo "    --endpoint-url http://localhost:4566 \\"
echo "    --access-key test \\"
echo "    --secret-key test \\"
echo "    --format json \\"
echo "    --output localstack-scan-results.json"
echo ""
echo "Generate SARIF output:"
echo "  java -jar target/cloud-policy-guard.jar scan-aws \\"
echo "    --region us-east-1 \\"
echo "    --endpoint-url http://localhost:4566 \\"
echo "    --access-key test \\"
echo "    --secret-key test \\"
echo "    --format sarif \\"
echo "    --output localstack-scan-results.sarif"
echo ""
echo "Scan with different failure threshold:"
echo "  java -jar target/cloud-policy-guard.jar scan-aws \\"
echo "    --endpoint-url http://localhost:4566 \\"
echo "    --fail-on critical"
echo ""
echo "🔧 SETUP & DEBUGGING"
echo "─────────────────────────────────────────────────"
echo ""
echo "View LocalStack logs:"
echo "  docker-compose logs localstack"
echo ""
echo "View LocalStack logs (follow):"
echo "  docker-compose logs -f localstack"
echo ""
echo "List all security groups in LocalStack:"
echo "  export AWS_ACCESS_KEY_ID=test"
echo "  export AWS_SECRET_ACCESS_KEY=test"
echo "  aws ec2 describe-security-groups \\"
echo "    --endpoint-url http://localhost:4566 \\"
echo "    --region us-east-1"
echo ""
echo "List only custom security groups:"
echo "  export AWS_ACCESS_KEY_ID=test"
echo "  export AWS_SECRET_ACCESS_KEY=test"
echo "  aws ec2 describe-security-groups \\"
echo "    --filters \"Name=group-name,Values=my-test-sg\" \\"
echo "    --endpoint-url http://localhost:4566"
echo ""
echo "Describe specific security group:"
echo "  export AWS_ACCESS_KEY_ID=test"
echo "  export AWS_SECRET_ACCESS_KEY=test"
echo "  aws ec2 describe-security-groups \\"
echo "    --group-ids sg-xxxxxxxx \\"
echo "    --endpoint-url http://localhost:4566"
echo ""
echo "📊 ANALYZE RESULTS"
echo "─────────────────────────────────────────────────"
echo ""
echo "Count violations in JSON report:"
echo "  jq '.violations | length' localstack-scan-results.json"
echo ""
echo "List all violations:"
echo "  jq '.violations[] | {rule, severity, resource}' localstack-scan-results.json"
echo ""
echo "Filter violations by severity:"
echo "  jq '.violations[] | select(.severity==\"HIGH\")' localstack-scan-results.json"
echo ""
echo "View violation details:"
echo "  jq '.violations[0]' localstack-scan-results.json"
echo ""
echo "🐛 TROUBLESHOOTING"
echo "─────────────────────────────────────────────────"
echo ""
echo "LocalStack won't start:"
echo "  1. Check Docker is running: docker version"
echo "  2. Check disk space: df -h"
echo "  3. View logs: docker-compose logs localstack"
echo ""
echo "Connection refused:"
echo "  1. Verify running: docker ps | grep localstack"
echo "  2. Wait longer: sleep 15 && [retry command]"
echo "  3. Health check: curl http://localhost:4566/_localstack/health"
echo ""
echo "No violations found:"
echo "  1. Verify security groups exist:"
echo "     aws ec2 describe-security-groups --endpoint-url http://localhost:4566"
echo "  2. Create or modify security groups with AWS CLI"
echo "  3. Verify policies are loaded"
echo ""
